version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: "kartoza/postgis:11.0-2.5"
    environment:
        POSTGRES_DB: openld_db
        POSTGRES_USER: openld
        POSTGRES_PASSWORD: openld
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data