version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: "mysql:latest"
    environment:
        MYSQL_DATABASE: openld_db
        MYSQL_ROOT_PASSWORD: openld
    ports:
      - "3306:3306"