--
-- PostgreSQL database dump
--

-- Dumped from database version 12.1 (Debian 12.1-1.pgdg100+1)
-- Dumped by pg_dump version 12.1 (Debian 12.1-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO openld;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: openld
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO openld;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO openld;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: openld
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO openld;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO openld;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO openld;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO openld;

--
-- Name: DeviceCodes; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."DeviceCodes" (
    "UserCode" character varying(200) NOT NULL,
    "DeviceCode" character varying(200) NOT NULL,
    "SubjectId" character varying(200),
    "ClientId" character varying(200) NOT NULL,
    "CreationTime" timestamp without time zone NOT NULL,
    "Expiration" timestamp without time zone NOT NULL,
    "Data" character varying(50000) NOT NULL
);


ALTER TABLE public."DeviceCodes" OWNER TO openld;

--
-- Name: Drawings; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."Drawings" (
    "Id" text NOT NULL,
    "Title" text,
    "OwnerId" text,
    "LastModified" timestamp without time zone NOT NULL
);


ALTER TABLE public."Drawings" OWNER TO openld;

--
-- Name: FixtureModes; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."FixtureModes" (
    "Id" text NOT NULL,
    "Name" text,
    "FixtureId" text NOT NULL,
    "Channels" integer
);


ALTER TABLE public."FixtureModes" OWNER TO openld;

--
-- Name: FixtureTypes; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."FixtureTypes" (
    "Id" text NOT NULL,
    "Name" text
);


ALTER TABLE public."FixtureTypes" OWNER TO openld;

--
-- Name: Fixtures; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."Fixtures" (
    "Id" text NOT NULL,
    "Name" text,
    "Manufacturer" text,
    "ReleaseDate" timestamp without time zone NOT NULL,
    "TypeId" text,
    "Power" integer NOT NULL,
    "Weight" real NOT NULL,
    "ImageId" text,
    "SymbolId" text
);


ALTER TABLE public."Fixtures" OWNER TO openld;

--
-- Name: Labels; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."Labels" (
    "Id" text NOT NULL,
    "ViewId" text NOT NULL,
    "Position" jsonb,
    "Text" text
);


ALTER TABLE public."Labels" OWNER TO openld;

--
-- Name: PersistedGrants; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."PersistedGrants" (
    "Key" character varying(200) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "SubjectId" character varying(200),
    "ClientId" character varying(200) NOT NULL,
    "CreationTime" timestamp without time zone NOT NULL,
    "Expiration" timestamp without time zone,
    "Data" character varying(50000) NOT NULL
);


ALTER TABLE public."PersistedGrants" OWNER TO openld;

--
-- Name: RiggedFixtures; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."RiggedFixtures" (
    "Id" text NOT NULL,
    "FixtureId" text,
    "StructureId" text NOT NULL,
    "Position" jsonb,
    "Address" smallint NOT NULL,
    "Universe" smallint NOT NULL,
    "ModeId" text,
    "Notes" text,
    "Angle" smallint NOT NULL,
    "Colour" text,
    "Name" text,
    "Channel" smallint DEFAULT 0 NOT NULL
);


ALTER TABLE public."RiggedFixtures" OWNER TO openld;

--
-- Name: StoredImages; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."StoredImages" (
    "Id" text NOT NULL,
    "Hash" text,
    "Path" text
);


ALTER TABLE public."StoredImages" OWNER TO openld;

--
-- Name: StructureTypes; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."StructureTypes" (
    "Id" text NOT NULL,
    "Name" text
);


ALTER TABLE public."StructureTypes" OWNER TO openld;

--
-- Name: Structures; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."Structures" (
    "Id" text NOT NULL,
    "ViewId" text NOT NULL,
    "Geometry" jsonb,
    "Name" text,
    "Rating" real NOT NULL,
    "TypeId" text,
    "Notes" text
);


ALTER TABLE public."Structures" OWNER TO openld;

--
-- Name: Symbols; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."Symbols" (
    "Id" text NOT NULL,
    "Hash" text,
    "Path" text,
    "BitmapId" text
);


ALTER TABLE public."Symbols" OWNER TO openld;

--
-- Name: Templates; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."Templates" (
    "Id" text NOT NULL,
    "DrawingId" text
);


ALTER TABLE public."Templates" OWNER TO openld;

--
-- Name: UserDrawings; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."UserDrawings" (
    "Id" text NOT NULL,
    "UserId" text,
    "DrawingId" text NOT NULL
);


ALTER TABLE public."UserDrawings" OWNER TO openld;

--
-- Name: Views; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."Views" (
    "Id" text NOT NULL,
    "DrawingId" text NOT NULL,
    "Name" text,
    "Type" integer NOT NULL,
    "Height" real DEFAULT 0 NOT NULL,
    "Width" real DEFAULT 0 NOT NULL
);


ALTER TABLE public."Views" OWNER TO openld;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: openld
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO openld;