version: "3.3"

services:
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    volumes:
      - openld-data:/openld-data
      - ${HOME}/.aspnet/certs:/certs/
    environment:
        ASPNETCORE_URLS: https://+;http://+
        ASPNETCORE_HTTPS_PORT: 443
        ASPNETCORE_Kestrel__Certificates__Default__Password: H@ye?fuGg:)OyHxSLmS?eMKtBI%U:;v]oe]udeC#_wT|*W7+
        ASPNETCORE_Kestrel__Certificates__Default__Path: /certs/openld-https.pfx
    restart: always
  db:
    image: "postgres:12.1"
    environment:
        POSTGRES_DB: openld_db
        POSTGRES_USER: openld
        POSTGRES_PASSWORD: openld
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-data/initdb.d:/docker-entrypoint-initdb.d/
    restart: always
volumes:
  postgres-data:
  openld-data: