version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/app
      - openld-data:/openld-data
  db:
    image: "postgres:12.1"
    environment:
        POSTGRES_DB: openld_db
        POSTGRES_USER: openld
        POSTGRES_PASSWORD: openld
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  openld-data: